### ISSUE TITLE
Course 

### ISSUE THREAD

**Issue by Deepakmalempati** [prasu93/express-mvc#1]
create a course

**Comment by prasu93** [comment]
- [x] Model Creation

**Comment by prasu93** [comment]
- [x] Sample Data Creation

**Comment by prasu93** [comment]
- [x] Data Seeding

**Comment by prasu93** [comment]
- [x] Routing the requests to Controller

**Comment by prasu93** [comment]
- [x] Controller Implementation(two Json calls,five View req,three data actions)

**Comment by prasu93** [comment]
- [x] Implementation of Views

**Comment by prasu93** [comment]
- [x] Updating application navigation for accessing the resource

**Comment by prasu93** [comment]
- [x] Updating application navigation for accessing the developer page

**Comment by prasu93** [comment]
- [x] Check the routing functionality

**Comment by prasu93** [comment]
- [x] Try with different data sets or objects

**Comment by prasu93** [comment]
All done
