### ISSUE TITLE
Section roles and responsibilities

### ISSUE THREAD

**Issue by prasu93** [prasu93/express-mvc#2]
Chaitanya...come on grab it!!!

**Comment by chaitanyapopuri** [comment]
- [x] creating the model (and properties)

**Comment by chaitanyapopuri** [comment]
- [x] creating sample data that fits the model

**Comment by chaitanyapopuri** [comment]
- [x] seeding the sample data

**Comment by chaitanyapopuri** [comment]
- [ ] routing requests to the  controller

**Comment by chaitanyapopuri** [comment]
- [ ] Implement the controller

**Comment by chaitanyapopuri** [comment]
- [ ]  Implementing the 5 views used to install/create/read/update/delete (CRUD).

**Comment by chaitanyapopuri** [comment]
- [ ] Updating the application navigation to provide access to the resource

**Comment by chaitanyapopuri** [comment]
- [ ] Updating the application navigation to provide access to the developer page

**Comment by chaitanyapopuri** [comment]
- [ ] Update everything

**Comment by chaitanyapopuri** [comment]
- [ ] Testing
