### ISSUE TITLE
Student

### ISSUE THREAD

**Issue by chaitanyapopuri** [prasu93/express-mvc#3]
This is student.

**Comment by Deepakmalempati** [comment]
- [x] creating the model (and properties),

**Comment by Deepakmalempati** [comment]
- [x] creating sample data that fits the model

**Comment by Deepakmalempati** [comment]
- [x] seeding your sample data

**Comment by Deepakmalempati** [comment]
- [ ] routing requests to your controller

**Comment by Deepakmalempati** [comment]
- [ ] implemention of controllers
 json calls, view requests, data actions (create/update/delete)

**Comment by Deepakmalempati** [comment]
- [ ] implementing the views, CRUD operations

**Comment by Deepakmalempati** [comment]
- [ ] update the application navigation

**Comment by Deepakmalempati** [comment]
- [ ] update the application navigation to provide access to your developer page.
